---
- name: Download VIM plugin Manager
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
    mode: '0440'

- name: Install Plugins for vimrc
  git:
    repo: https://github.com/fatih/vim-go.git
    dest: ~/.vim/pack/plugins/start/vim-go
    update: yes
    single_branch: yes
    version: master

- name: Setup vimrc
  copy:
    src: ../configs/vim/.vimrc
    dest: "~/.vimrc"
    backup: yes
